### ISSUE TITLE
Cant put the module in the fluid pipe.

### ISSUE THREAD

**Issue by MarobsKoco** [Quarris/PrettyFluidPipes#10]
I tryed every thing, from using the normal pipes to only the fluid pipe. but i cant put the modules in the pipes to extract or retrieval. dont know what is going on with it. but it doesnt seem to work. im on the 1.18.2 and use forge 40.1.73

**Comment by Trogdayton** [comment]
I'm having the same issue, with the Caveopolis pack, 1.18.2 with forge 40.1.68. I can insert the fluid modules into the regular pipes, weirdly, but there's no interface for the fluid pipes. PFP is 1.0.0

**Comment by specialworld** [comment]
Having the same issue with a custom modpack

**Comment by Quarris** [comment]
I'll be honest, the newest version of pretty pipes changed quite a few things. I won't be updating the current version and instead at some point will completely rework the code but I just don't have the time right now
