### ISSUE TITLE
Feature Request: Better handling of broken pipes

### ISSUE THREAD

**Issue by MuteTiefling** [Quarris/PrettyFluidPipes#2]
Consider the following scenario:

Player has a very long pipe between source and destination. The destination tank can hold a large amount of fluid. 512 buckets, for example. They hook everything up and stuff starts to flow.... but no they don't want the destination there. So they break the tank and move it.

Now, that very long pipe, it was already full of fluids. 512 buckets of fluid... it just lost it's destination and starts to spill out the end. And keeps spilling out the end. Even though there's another valid destination on the network.

Rather than spilling out automatically when it hits the expected output and doesn't find it, it should be able to re-route and seek another tank. If there's no valid output for it on the network, then it spills. But right now it's a little bit wonky to have buckets and buckets spilling out despite there being a valid output tank.

**Comment by MuteTiefling** [comment]
Video example: https://streamable.com/od5nek

**Comment by Quarris** [comment]
Will watch it as soon as it is processed. This might be a bug since the fluids are supposed to find another destination until they can't. Will test and sort it out if that is the case.

**Comment by MuteTiefling** [comment]
Awesome, thanks!

**Comment by Quarris** [comment]
Yeah I did some tests and the same thing happens with the items and chests. I found where the issue is and I hope Ellpeck can fix a fix for it. If he does then this should fix most of the problems that the fluids are having right now

**Comment by Quarris** [comment]
Yeah okay. Same happens with items with the base mod and I cannot really override this behaviour without entirely reconstructing the base mod.
"Meddling with the pipe network is supposed to cause items to drop."

**Comment by MuteTiefling** [comment]
Sounds good. Thanks for looking into it!
