### ISSUE TITLE
Crash using fluid and non fluid modules in same pipe

### ISSUE THREAD

**Issue by Owningle** [Quarris/PrettyFluidPipes#7]
I placed a pipe with a fluid filter, and a non fluid extraction module, the server crashed, and won't load.
I have fixed it by temporarily removing the mod.
Crash Report: https://pastebin.com/GtmP2Ux7

**Comment by Quarris** [comment]
Was the pipe a fluid pipe or a normal pipe?

**Comment by Owningle** [comment]
A normal pipe

**Comment by Quarris** [comment]
Yeah you need a fluid pipe for fluid modules, I will work on fixing it so that you can't insert fluid modules into non-fluid pipes

**Comment by Quarris** [comment]
Should be fixed in v0.4.2
