### ISSUE TITLE
[1.18.2] Crash using the new version of Pretty Pipes

### ISSUE THREAD

**Issue by Vapaman** [Quarris/PrettyFluidPipes#9]
**Description**
After updating the mod, entering a world with fluids already placed in them crashes the game.

**Crash Report**
https://pastebin.com/y6MYzmRa

**Mod versions**
- PrettyPipesFluids-1.18.2-1.0.0
- PrettyPipes-1.12.5

P.S. The fluid pipes don't seem to work correctly after the update. You can't insert upgrades into them.

**Comment by Saereth** [comment]
can confirm, same issue, can't insert the upgrades so the mod is basically unusable currently.

**Comment by Quarris** [comment]
I'll be honest, the newest version of pretty pipes changed quite a few things. I won't be updating the current version and instead at some point will completely rework the code but I just don't have the time right now

**Comment by Quarris** [comment]
Btw I just uploaded a new version for 1.18.2 and I think it should work now. Please let me know if there are still issue with v1.0.1

**Comment by Saereth** [comment]
Great news I'll test today
